### ISSUE TITLE
Error message in defferent codepage (Windows OS)

### ISSUE THREAD

**Issue by yenesey** [nospaceships/node-os-service#28]
I'am use os-service under Windows 10 (RU):
```
service.add(......... , function(error) {
  if (error)
    console.error(error);
});
```

When insufficient privelegies, or service already exist, error received:
Error: CreateService() failed: ��������� ������ ��� ����������.

Thouht exact message text comes from OS, and try:
 `err = iconv.decode(new Buffer(error.message), 'cp1251').toString()`

, no effect, unfortunately

**Comment by stephenwvickers** [comment]
Hi,

Apologies for the delay in my response, this is likely due to the fact we don't use multi-byte character strings (e.g. using CreateServiceW vs CreateServiceA, and correctly handling strings).

If you would like to change this behaviour and have the module correctly handle multi-byte strings I would suggest forking the repo, making the appropriate changes, and create a Pull Request.

Unfortunately I don't have the time to perform this myself, so I would be looking for a Pull Request to support it.

Steve
