### ISSUE TITLE
Windows run error 1053: the service did not respond to the start or control request in a timely fashion

### ISSUE THREAD

**Issue by JestDotty** [nospaceships/node-os-service#29]
```js
var fs = require('fs')

var service = require('os-service')

var name = 'screeps-agent'
var action = process.argv[2] || 'add'

switch(action){
  case 'add':
    service.add(name, {programPath: ['C:\\Program Files\\nodejs\\node_modules\\screepsplus-agent\\app.js']}, (err)=>{
      if(err) throw err
    })
    break;
  case 'remove':
    service.remove(name, (err)=>{
      if(err) throw err
    })
    break;
  case 'run':
    service.run(fs.createWriteStream(name+'.log'), ()=>{
      service.stop()
    })
    break;
}
```

Path to executable (from services): `"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\screepsplus-agent\app.js"`

Result:
![image](https://cloud.githubusercontent.com/assets/4729968/25549523/4f0832e4-2c40-11e7-9298-a72946cb7592.png)

(doing run using os-service just hangs indefinitely with no msg and service is still not active)

manual run (copy pasted path to executable):
![image](https://cloud.githubusercontent.com/assets/4729968/25549508/3a54bd68-2c40-11e7-80ab-c1c1b78442f1.png)

**Comment by stephenwvickers** [comment]
Generally errors like this are down to being in the wrong directory when the program starts, i.e. the current working directory.  Node doesn't know which directory in which to look for modules basically.

I would advise at the very top of the script to do this:

```javascript
process.chdir(__dirname)
```

As per:

https://www.npmjs.com/package/os-service#current-working-directory

Steve

**Comment by JestDotty** [comment]
That's an absolute path...?

**Comment by stephenwvickers** [comment]
Yes that's right. It would require modules under a node_modules directory in the directory the script is located.

**Comment by JestDotty** [comment]
Would there be a way to fix that?

This isn't my module that I am trying to run as a service BTW. I just
wanted an easy way to run a script so it doesn't make a window in windows.
I've done it before with another service module but idr which one it was...

**Comment by stephenwvickers** [comment]
Ah, okay, that makes sense.

You're going to struggle a little with this one, since the app.js script doesn't behave like a service, i.e. it does't call the service.run() function.

Perhaps your best way is to implement a wrapper script which starts as a service, and then runs the app.js script as a child process.

Or, you could fork the screepsplus agent repo, and modify it.

Steve

**Comment by actiontom** [comment]
I've managed to get os-service to create a service from my node app. Once it’s created I try to start the service manually via net start “myservice”. The service then eventually times out but I’ve tested it while it’s “starting” and its working fine. It’s as if something isn’t telling Windows the service is running fine. I then get this message.
The PosRouter service failed to start due to the following error: 
**The service did not respond to the start or control request in a timely fashion**.
This is what the code looks like for the node.js app that kicks off the service which is another node.js app.
![image](https://user-images.githubusercontent.com/17963282/44522546-35777200-a6d7-11e8-927e-b2f85133f5f4.png)
I've also tried increasing the ServicesPipeTimeout for service in Windows but it still times out eventually - while it's actually working before the timeout happens. 
Any ideas on what I could be doing wrong?

**Comment by stephenwvickers** [comment]
Hi @JestDotty 

From what I can see you are not passing the `run` argument to your service but you check for it in the main outer if/else if statement - your program is likely just logging `Nothing happened` from the last clause.

Try adding:

```
programArgs: ["unused", "run"]
```

To your `options` object.  Note that since you check for `run` in `process.argv[3]` I have added the `unused` argument at position 0 above since I don't know what you expect there.

Steve
