### ISSUE TITLE
Remove support to override stdout/stderr with a logstream (let users use their required/own logging modules)

### ISSUE THREAD

**Issue by mramos-dev** [nospaceships/node-os-service#35]
I'm getting a "The service did not respond to the start or control request in a timely fashion." error on Windows 10 when starting a service using your most recent version published to npm, 1.5.0. I have no problems when running 1.4.2. The module did build successfully on installation and there are no error bubbling up from the run function and I don't see any method of enabling logging for this module (though I may just be missing something). Let me know if you need any other detail I may have omitted. Thanks.

**Comment by mramos-dev** [comment]
This is also a issue in Linux since our builds which run in docker containers were failing because of this.

**Comment by stephenwvickers** [comment]
Hi @MRamos62786 

Odd, the `example\periodic-logger.js` program in the repo installs and starts for me.

What version of node are you running, and what modules do you include/use?  Does this include any logging modules?

The only change in this build it could be would be:

https://github.com/stephenwvickers/node-os-service/commit/40e8b75a21a28971156946ca4d6e9ec90f4b2a50

Steve

**Comment by AndyDBell** [comment]
I am experiencing the same "_Windows could not start the service on Local Computer. Error 1053: The service did not respond to the start or control request in a timely fashion_" problem with version 1.5.0

My code does work with version 1.4.2 and yes, I am using a logging package. I am using Bunyan.  Prior to hanging with the 1503 error, my code creates a log file. However no log entries are written to the file.

**Comment by mramos-dev** [comment]
@AndyDBell Could you try out my fix to see if it works for you as well? https://github.com/stephenwvickers/node-os-service/pull/38

**Comment by mramos-dev** [comment]
@stephenwvickers To answer you question about logging, yes, we have a logging module we've developed in-house.

**Comment by stephenwvickers** [comment]
I believe this issue will be due to the changes to the logging setup by this module.  This falls inline with the issues users have reported, and is also the only relevant change between versions.

Given the different ways node versions support overriding stdout/stderr I think it's about time we removed the code that fiddles with those variables, and let users utilise their required logging modules to do this.  I don't believe I have ever seen anything useful in the log (from the os-service code that is) so it will be safe to remove.

I will make the change and publish a new version, then notify here.

**Comment by stephenwvickers** [comment]
Version 2.0.0 of os-service has been published to npm.  Note that the `run()` function now only takes 1 argument, the stop callback function.
